site_name: Marlinraker Documentation
site_url: https://marlinraker.readthedocs.io
repo_url: https://github.com/pauhull/marlinraker
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - index.md
  - installation.md
  - configuration.md
  - security.md
  - Advanced:
    - advanced/macro-scripting.md
    - advanced/update-manager.md
    - advanced/cli-arguments.md
    - advanced/developing.md
theme:
  name: material
  palette:
    scheme: slate
    primary: green
  icon:
    repo: fontawesome/brands/github