# Generic 3D Printer

[printer]
bed_mesh = false
print_volume = [220, 220, 240]

[printer.extruder]
min_temp = 0
max_temp = 250
min_extrude_temp = 180

[printer.heater_bed]
min_temp = 0
max_temp = 100

[macros.pause]
rename_existing = "pause_base"
gcode = """
pause_base
G91
G1 Z5 E-20 F600
G90
G1 X0 Y0 F6000
"""

[macros.resume]
rename_existing = "resume_base"
gcode = """
G91
G1 Z-5 E20 F600
resume_base
"""

[macros.cancel_print]
rename_existing = "cancel_base"
gcode = """
cancel_base
G28 X Y
M18
M104 S0
M140 S0
M107
"""